# OpenList 官方标准完整版（非 lite）
IMAGE=openlistteam/openlist:latest
AUTOSTART=1

# OpenList 配置与数据库持久化目录
VOLUME=/data/adb/dockroot/volumes/openlist:/opt/openlist/data

ENV=UMASK=022

CHECK_PORT=5244
HEALTH_URL=http://127.0.0.1:5244/
