# 青龙官方 latest 镜像
IMAGE=whyour/qinglong:latest
AUTOSTART=1
HOSTNAME=qinglong

# 青龙配置、任务、日志和依赖均持久化到 /ql/data
VOLUME=/data/adb/dockroot/volumes/qinglong:/ql/data

ENV=QlPort=__QL_PORT__
ENV=QlBaseUrl=/
ENV=TZ=Asia/Shanghai
